
name: Github-coPilot Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  HyperExecute-Playwright:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone https://github.com/gagan-lambda/contosotraders-cloudtesting.git
          echo "STEP 2) Download CLI and setting environment variables"
              cd src/ContosoTraders.Ui.Website
              npm install
              npm run start &
              curl https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute -o hyperexecute
              chmod u+x hyperexecute
            ./hyperexecute --user gagandeepb --key KZCghqXcnDAkO3kuErqkRKoQGgzXzzV95L4gJSf7dIaJPpCzpL  --config hyperexecute-matrix.yaml
